server:
  port: 8080

spring:
  jpa:
    open-in-view: false
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    # 修改了数据库端口
    url: jdbc:mysql://mysql:3306/jiang_donation?useSSL=false&allowPublicKeyRetrieval=true
    username: username
    password: password # 修改了数据库密码
  data:
    redis:
      host: redis # localhost 
      port: 6379

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.mapper
  configuration:
    # 开启驼峰命名
    map-underscore-to-camel-case: true

logging:
  level:
    com:
      example:
        mapper: debug
        service: debug
        controller: debug

donation:
  jwt:
    # 设置 jwt 签名加密时使用的秘钥
    admin-secret-key: ThisIsASecureKeyWithAtLeast64BytesLength1234567890123456789012345678901234567890123456789012345678901234
    # 设置 jwt 过期时间
    admin-ttl: 36000000
    # 设置网页传递过来的令牌名称
    admin-token-name: Authorization

    # 密钥
    user-secret-key: ThisIsASecureKeyWithAtLeast64BytesLength1234567890123456789012345678901234567890123456789012345678901234

    user-ttl: 36000000
    # 设置传递过来的令牌名称
    user-token-name: Authorization

  aliyun:
    endpoint: 
    access-key-id: 
    access-key-secret: 
    bucket-name: 

# 百度地图 API Key
baidu:
  map:
    api:
      key: 
